package de.ngloader.wuppy;

import java.io.File;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.mojang.realmsclient.gui.ChatFormatting;

import de.ngloader.wuppy.handler.GlobalEventHandler;
import de.ngloader.wuppy.modmanager.ModList;
import de.ngloader.wuppy.modmanager.ModManager;
import de.ngloader.wuppy.sound.WuppySounds;
import net.minecraft.client.Minecraft;
import net.minecraft.util.text.TextFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = Wuppy.MODID, version = Wuppy.VERSION)
public class Wuppy {
	public static Wuppy INSTANCE;

	public static final String MODID = "wuppy";
	public static final String VERSION = "1.0";
	public static final String ASSETS_LOCATION = "wuppy:";

	public static final Random RANDOM = new Random();

	public static final Logger LOGGER = LogManager.getLogger("Wuppy");

	public static final String PREFIX = TextFormatting.AQUA + "[" + TextFormatting.DARK_AQUA + "Wuppy" + TextFormatting.AQUA + "] ";

	public Wuppy() {
		INSTANCE = this;
	}

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		setModMetadata(event.getModMetadata());

		try {
			WuppySounds.reigsterAllSounds();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		try {
			File folder = Minecraft.getMinecraft().mcDataDir;

			new ModManager(Minecraft.getMinecraft());

			GlobalEventHandler wuppyEventHandler = new GlobalEventHandler();
			MinecraftForge.EVENT_BUS.register(wuppyEventHandler);
			FMLCommonHandler.instance().bus().register(wuppyEventHandler);
		} catch (Exception ex) {
			ex.printStackTrace();
		}

		Runtime.getRuntime().addShutdownHook(new Thread(this::end));
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
	}

	public void setModMetadata(ModMetadata data) {
		data.autogenerated = false;
		data.name = ChatFormatting.RED + "Wuppy";
		data.description = "Coming soon";
		data.credits = "Dragon0697";
		data.logoFile = "assets/wuppy/textures/logo/logo.png";

		List<String> authors = new LinkedList<String>();

		authors.add("NilssMiner99");

		data.authorList = authors;
	}

	public void end() {
	}
}
